default_per_page:     "10"
database_username:    ""
github_access_token:  ""
ga_tracking_id:       ""
recaptcha_site_key:   ""
recaptcha_secret_key: ""
secret_key:           ""

production:
  database_username: ""
  database_password: ""
