database_username:    ""
github_access_token:  ""
default_per_page:     "10"
recaptcha_site_key:   ""
recaptcha_secret_key: ""
secret_key:           ""

production:
  database_username: ""
  database_password: ""
  secret_key:        ""
