default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <%= Figaro.env.database_username %>
  password: <%= Figaro.env.database_password %>

development:
  <<: *default
  database: weight_of_it_development

test:
  <<: *default
  database: weight_of_it_test

production:
  <<: *default
  host: localhost
  database: weight_of_it
